## Count scaled (standard), race and agefirst labelencoded

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('data-training.csv')

In [3]:
from random import sample

In [4]:
dfnew = df.replace({9: np.nan})

In [5]:
dfnew['agegrp'] = dfnew['agegrp'].fillna(value=9)

In [6]:
dfnew.loc[dfnew.menopaus == 0.0, 'surgmeno'] = 0.0

In [7]:
dfnew.loc[dfnew.menopaus == 0.0, 'hrt'] = 0.0

In [8]:
def fill_func(col):
    listval = sample(list(dfnew[dfnew[col].isna()==False][col].values),len(dfnew[dfnew[col].isna()][col])) 
    fill = pd.DataFrame(index =dfnew.index[dfnew[col].isnull()], data= listval,columns=[col])
    dfnew.fillna(fill,inplace = True)
    dfnew[col] = dfnew[col].astype(float)

In [9]:
cols = np.array(dfnew.columns)

In [10]:
for col in cols[1:]:
    fill_func(col)

In [11]:
dfnew.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196462 entries, 0 to 196461
Data columns (total 16 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   id        196462 non-null  object 
 1   menopaus  196462 non-null  int64  
 2   agegrp    196462 non-null  float64
 3   density   196462 non-null  float64
 4   race      196462 non-null  float64
 5   Hispanic  196462 non-null  float64
 6   bmi       196462 non-null  float64
 7   agefirst  196462 non-null  float64
 8   nrelbc    196462 non-null  float64
 9   brstproc  196462 non-null  float64
 10  lastmamm  196462 non-null  float64
 11  surgmeno  196462 non-null  float64
 12  hrt       196462 non-null  float64
 13  invasive  196462 non-null  float64
 14  cancer    196462 non-null  float64
 15  count     196462 non-null  float64
dtypes: float64(14), int64(1), object(1)
memory usage: 24.0+ MB


In [17]:
dfnew.corr()['cancer'].sort_values(ascending=True)

race              -0.050968
Hispanic          -0.047672
other             -0.028965
nrelbc            -0.027750
Native American   -0.027341
lastmamm          -0.024797
Asian             -0.024526
count             -0.024490
bmi               -0.020833
brstproc          -0.014091
black             -0.013826
surgmeno          -0.013398
agefirst          -0.007685
menopaus          -0.000664
hrt                0.009321
density            0.023681
agegrp             0.026089
white              0.052184
invasive           0.874999
cancer             1.000000
Name: cancer, dtype: float64

In [12]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
dfnew = dfnew.join(pd.DataFrame(lb.fit_transform(dfnew['race']),
                          columns=['white', 'Asian', 'black', 'Native American', 'other'], 
                          index=dfnew.index))

### PCA analysis

In [59]:
y_train.unique()

array([0., 1.])

In [59]:
from sklearn.decomposition import PCA

In [62]:
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x_train.drop(['invasive'],axis=1))
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['p1', 'p2'])

In [63]:
principalDf.head()

p1        p2
0  4.421795  0.471419
1  4.422332  0.476627
2  4.419836  0.474596
3  4.419836  0.474596
4  4.440110  0.546217

In [24]:
from sklearn.linear_model import LogisticRegression

In [71]:
lr = LogisticRegression(max_iter=1000)

In [72]:
lr.fit(principalDf, y_train)

LogisticRegression(max_iter=1000)

In [54]:
y_train_pred = cross_val_predict(lr, principalDf, y_train, cv=10) 

In [55]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

C:\Users\abhij\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


0.0
0.0
0.0


In [73]:
np.unique(lr.predict(principalDf))

array([0.])

### PCA Analysis ends

In [32]:
x_train = dfnew.drop(['id','cancer','race'],axis=1)
y_train = dfnew['cancer']

In [37]:
x_train = dfnew.drop(['id','cancer','race','agefirst'],axis=1)
y_train = dfnew['cancer']

In [14]:
testdf = pd.read_csv('data-provisional.csv')

In [15]:
testdfnew = testdf.replace({9: np.nan})

In [16]:
testdfnew['agegrp'] = testdfnew['agegrp'].fillna(value=9)

In [17]:
testdfnew.loc[testdfnew.menopaus == 0.0, 'surgmeno'] = 0.0
testdfnew.loc[testdfnew.hrt == 0.0, 'hrt'] = 0.0

In [18]:
def fill_func(col):
    listval = sample(list(testdfnew[testdfnew[col].isna()==False][col].values),len(testdfnew[testdfnew[col].isna()][col])) 
    fill = pd.DataFrame(index =testdfnew.index[testdfnew[col].isnull()], data= listval,columns=[col])
    testdfnew.fillna(fill,inplace = True)
    testdfnew[col] = testdfnew[col].astype(float)

In [19]:
cols = np.array(testdfnew.columns)

In [20]:
for col in cols[1:]:
    fill_func(col)

In [21]:
from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()
testdfnew = testdfnew.join(pd.DataFrame(lb.fit_transform(testdfnew['race']),
                          columns=['white', 'Asian', 'black', 'Native American', 'other'], 
                          index=testdfnew.index))

In [46]:
lb = LabelBinarizer()
testdfnew = testdfnew.join(pd.DataFrame(lb.fit_transform(testdfnew['agefirst']),
                          columns=['Child1','Child2','NoChild'], 
                          index=testdfnew.index))

In [25]:
x_test['count'] = testdfnew['count'].apply(lambda x: x if x<=3 else 4)

In [23]:
x_test = testdfnew.drop(['id','race'],axis=1)

In [24]:
x_test.head()

menopaus  agegrp  density  Hispanic  bmi  agefirst  nrelbc  brstproc  \
0         0     1.0      1.0       0.0  1.0       0.0     0.0       0.0   
1         0     1.0      1.0       0.0  2.0       0.0     1.0       0.0   
2         0     1.0      1.0       0.0  2.0       0.0     0.0       0.0   
3         0     1.0      1.0       0.0  2.0       1.0     1.0       0.0   
4         0     1.0      1.0       0.0  3.0       2.0     0.0       0.0   

   lastmamm  surgmeno  hrt  invasive  count  white  Asian  black  \
0       0.0       0.0  0.0       0.0    4.0      1      0      0   
1       1.0       0.0  1.0       0.0    1.0      1      0      0   
2       0.0       0.0  1.0       0.0    4.0      1      0      0   
3       0.0       0.0  1.0       0.0    2.0      1      0      0   
4       0.0       0.0  1.0       0.0    3.0      1      0      0   

   Native American  other  
0                0      0  
1                0      0  
2                0      0  
3                0      0  
4                0      0

In [19]:
x_train['count'] = dfnew['count'].apply(lambda x: x if x<=3 else 4)

In [36]:
x_train.head()

menopaus  agegrp  density  Hispanic  bmi  agefirst  nrelbc  brstproc  \
0         0     1.0      1.0       0.0  1.0       0.0     0.0       0.0   
1         0     1.0      1.0       0.0  1.0       0.0     0.0       0.0   
2         0     1.0      1.0       0.0  1.0       0.0     1.0       0.0   
3         0     1.0      1.0       0.0  1.0       0.0     1.0       0.0   
4         0     1.0      1.0       0.0  1.0       1.0     0.0       0.0   

   lastmamm  surgmeno  hrt  invasive     count  white  Asian  black  \
0       0.0       0.0  0.0       0.0 -0.118601      1      0      0   
1       0.0       0.0  0.0       0.0 -0.081960      1      0      0   
2       0.0       0.0  0.0       0.0 -0.136921      1      0      0   
3       0.0       0.0  0.0       0.0 -0.136921      1      0      0   
4       0.0       0.0  0.0       0.0 -0.118601      1      0      0   

   Native American  other  
0                0      0  
1                0      0  
2                0      0  
3                0      0  
4                0      0

In [104]:
dfnew['count'].describe()

count    196462.000000
mean          8.482852
std          54.631966
min           1.000000
25%           1.000000
50%           1.000000
75%           3.000000
max        7295.000000
Name: count, dtype: float64

In [33]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler = StandardScaler()

In [99]:
scaler.fit_transform(x_train[{'count'}])

array([[-0.11866438],
       [-0.08205568],
       [-0.13696872],
       ...,
       [ 6.76377067],
       [20.56524946],
       [-0.08205568]])

In [34]:
scaled_data = pd.DataFrame(scaler.fit_transform(dfnew[{'count'}]),
                          columns=['count'], 
                          index=x_train.index)

In [35]:
x_train['count'] = scaled_data['count']

In [66]:
scaled_data = pd.DataFrame(scaler.fit_transform(x_test[{'count'}]),
                          columns=['count'], 
                          index=x_test.index)

In [67]:
x_test['count'] = scaled_data['count']

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 42)

In [51]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(C=0.01)

In [52]:
lr.fit(x_train, y_train)

LogisticRegression(C=0.01)

In [53]:
roc_auc_score(y_train, lr.predict(x_train))

0.8858128834355828

In [24]:
y_train_pred = cross_val_predict(lr, x_train, y_train, cv=10) 

In [25]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

1.0
0.7627300613496932
0.8653963281997737


In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
knn = KNeighborsClassifier()

In [56]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_train_pred = cross_val_predict(knn, x_train, y_train, cv=10) 

In [ ]:
y_pred = knn.predict(x_train) 

In [30]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

0.4604746188904605
0.4493865030674847
0.4548629977489716


In [57]:
roc_auc_score(y_train, knn.predict(x_train))

KeyboardInterrupt: 

In [ ]:
from sklearn import metrics

In [ ]:
print(metrics.accuracy_score(y_train,y_pred))

In [25]:
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

In [27]:
y_train_pred = cross_val_predict(rf, x_train, y_train, cv=10) 

In [28]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

0.6548558127505496
0.7766871165644171
0.7105872447905703


In [124]:
predic = lr.predict(x_test)
pid = testdfnew['id'].array
d = {'id' : pid,'prediction':predic}
savedat = pd.DataFrame(d)
savedat.to_csv('lr_scaled_encodedrace.csv',index=False)

In [126]:
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 20, stop = 100, num = 5)]

# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 20, num = 4)]
max_depth.append(None)

# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]

# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]

# Method of selecting samples for training each tree
#bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               #'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf #,
               #'bootstrap': bootstrap
              }
print(random_grid)

{'n_estimators': [20, 40, 60, 80, 100], 'max_depth': [5, 10, 15, 20, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4]}


In [127]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state = 42)

In [146]:
grid_search = GridSearchCV(estimator = rf, param_grid = random_grid, 
                          cv = 5, n_jobs = -1, verbose = 2)

In [147]:
grid_search.fit(x_train, y_train)

Fitting 5 folds for each of 225 candidates, totalling 1125 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 15, 20, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [20, 40, 60, 80, 100]},
             verbose=2)

In [148]:
grid_search.best_params_

{'max_depth': 5,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 20}

In [149]:
best_rf = RandomForestClassifier(bootstrap = True, max_depth = 5, min_samples_leaf = 1,
                                 min_samples_split = 2, n_estimators = 20, random_state = 42)

In [150]:
y_train_pred = cross_val_predict(best_rf, x_train, y_train, cv=10) 

In [151]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

1.0
0.7716257668711657
0.871093411825816


In [153]:
best_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=20, random_state=42)

In [172]:
predic = lr.predict(x_test)
pid = testdfnew['id'].array
d = {'id' : pid,'prediction':predic}
savedat = pd.DataFrame(d)
savedat.to_csv('solution.csv',index=False)

In [88]:
from sklearn.svm import SVC
svc = SVC()

In [ ]:
from sklearn.model_selection import GridSearchCV
para = {'C': [0.01,0.1,1,10,100], 'gamma' : [10,1,0.1,0.001]}
grid = GridSearchCV(svc, para, refit = True, verbose = 2,cv=5,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


In [ ]:
svc.fit(x_train,y_train)

In [ ]:
y_train_pred = cross_val_predict(sgd, x_train, y_train, cv=10) 

In [ ]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

In [45]:
from sklearn.linear_model import SGDClassifier

In [46]:
sgd = SGDClassifier(max_iter=1000, tol=1e-3,early_stopping=True)

In [47]:
sgd.fit(x_train,y_train)

SGDClassifier(early_stopping=True)

In [86]:
y_train_pred = cross_val_predict(sgd, x_train, y_train, cv=10) 

In [87]:
print(precision_score(y_train, y_train_pred))
print(recall_score(y_train, y_train_pred))
print(f1_score(y_train, y_train_pred))

1.0
0.7716257668711657
0.871093411825816


In [48]:
from sklearn.metrics import roc_auc_score

In [50]:
roc_auc_score(y_train, sgd.predict(x_train))

0.8857361963190185